pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'marcosmrls/golang-junit:latest'  // Tu imagen personalizada
                    reuseNode true
                    args '--platform linux/amd64 -e GOCACHE=/tmp/go-build'  // Clave: define GOCACHE aquí
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'  // Ya no necesitas el export aquí
                }
            }
        }

        stage('Unit Test - Frontend'){
            agent{
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps{
                dir('bugtracker-frontend'){
                    sh '''
                        npm ci
                        npm test
                    '''
                }
            }
        }
    }
}