pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            steps {
                dir('bugtracker-backend') {  // <- Abre el bloque con {
                    sh 'go test -v ./...'   // Este comando se ejecutará dentro de bugtracker-backend
                }                            // <- Cierra el bloque con }
            }
        }
    }
}